var greeting = "Hello, everybody!"
var greetSpecialGuest = "Hello, " + specialGuest + "!"
var specialGuest = "Niel deGrasse Tyson"
var conversation = "'Let\'s talk about " + topic + "."
var topic = "test"
